[package]
name = "xmas-2025"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.22", features = ["csr"] }
yew-router = "0.19"
web-sys = "0.3"

[dev-dependencies]
trunk = "0.21.14"
